"""init

Revision ID: 6024e01b185a
Revises: 
Create Date: 2020-11-02 16:25:43.619427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6024e01b185a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('menuitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moduleId', sa.Integer(), nullable=True),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['moduleId'], ['module.id'], name=op.f('fk_menuitem_moduleId_module')),
    sa.ForeignKeyConstraint(['parentId'], ['menuitem.id'], name=op.f('fk_menuitem_parentId_menuitem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menuitem'))
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], name=op.f('fk_post_author_user')),
    sa.ForeignKeyConstraint(['module'], ['module.id'], name=op.f('fk_post_module_module')),
    sa.ForeignKeyConstraint(['parent'], ['post.id'], name=op.f('fk_post_parent_post')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_table('usermodules',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('moduleId', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moduleId'], ['module.id'], name=op.f('fk_usermodules_moduleId_module')),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_usermodules_userId_user')),
    sa.PrimaryKeyConstraint('userId', 'moduleId', name=op.f('pk_usermodules'))
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('browser', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], name=op.f('fk_userprofile_userid_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userprofile'))
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moduleId', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['moduleId'], ['menuitem.id'], name=op.f('fk_article_moduleId_menuitem')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('userprofile')
    op.drop_table('usermodules')
    op.drop_table('post')
    op.drop_table('menuitem')
    op.drop_table('user')
    op.drop_table('module')
    # ### end Alembic commands ###
